### ISSUE TITLE
Support for adding a Chunk (not EmptyChunk) to an EmptyRegion

### ISSUE THREAD

**Issue by brychrwolf** [matcool/anvil-parser#11]
Hello,

I would like to use your project to iterate over all mca files in a folder, and only save chunks which match a list coordinates. The problem I have is that there is no way to pass the output of getchunk, to setchunk as you know, Chunks are not EmptyChunks. 

No errors actually occur until I call save which tries to access sections... which don't exist the same in both types. I tried iterating over over all blocks in a chunk, and adding them to an EmptyRegion with set_block, and its almost okay, except some things are invisible (like signs). 

Is there any way you could make it possible to pass add a Chunk to an EmptyRegion and then be able to save that to a file?

**Comment by matcool** [comment]
Added in 0c886f4
