### ISSUE TITLE
Add NBT TileEntities values to block properties

### ISSUE THREAD

**Issue by Baterka** [matcool/anvil-parser#18]
I need to access block's PersistentData what are located in "TileEntities". Is there any way to implement it so I can parse those data per block?

As I see now it parsing just "properties" directly from Sections.

**Comment by matcool** [comment]
Just added `Chunk.get_tile_entity(x, y, z)` in 0.8.3, which returns a "raw" compound tag

**Comment by Baterka** [comment]
You're legend! Thanks :)
