### ISSUE TITLE
Max number of chunks in region file?

### ISSUE THREAD

**Issue by DoomSkullDeadly** [matcool/anvil-parser#19]
Ok so i'm not sure if it's me being stupid, but according to the minecraft wiki there are only 32x32 chunks in a single region file, however I've been able to call far beyond that without any errors being raised. Is there some kind of loop that makes it go back to the start of the region file when you call beyond it's limits?
![code1](https://user-images.githubusercontent.com/63046898/102068765-c61c7380-3df4-11eb-9993-ccffbe8f23dc.png)
the screenshot of the code which works without raising errors.

**Comment by DoomSkullDeadly** [comment]
I've also just tested the loop hypothesis, and yes it'll just loop back to the start of the region. It explains a lot, so I guess not really an issue.

**Comment by matcool** [comment]
What causes this "issue" is this line https://github.com/matcool/anvil-parser/blob/master/anvil/region.py#L33
```py
return 4 * (chunk_x % 32 + chunk_z % 32 * 32)
```
due to the modulos, a `chunk_x` of 1 and 33, for example, will result in the same chunk
