### ISSUE TITLE
Alternatives in different languages?

### ISSUE THREAD

**Issue by SJS830** [matcool/anvil-parser#2]
This repo is really cool but I was wondering if there was something similar for c++

**Comment by matcool** [comment]
no hablo español

**Comment by matcool** [comment]
you can beg @geniiii to do it in c++

**Comment by geniiii** [comment]
![Thiscatisr](https://user-images.githubusercontent.com/24881499/76362164-31e32480-6329-11ea-8139-21e90a88a4ca.gif)
