### ISSUE TITLE
Block Storage Format Breaks 20w17a and later worlds

### ISSUE THREAD

**Issue by Sevadus** [matcool/anvil-parser#9]
It looks like the new block storage format breaks things from snapshot 20w17a and on.

See https://minecraft.gamepedia.com/Java_Edition_20w17a#General_2 under "Changes">"General">"Block Storage Format"

Screenshot from my discord of infinite_zero better describing the issue than me. 
![Screenshot_20200531-081157](https://user-images.githubusercontent.com/3721264/83355805-84bfed00-a316-11ea-9c9b-f7d8643626b2.png)

**Comment by spiwn** [comment]
I have implemented a check for version in chunk.py. If it is greater or equal to Snapshot 20w17a the code does not stretch values between multiple longs.
https://github.com/spiwn/anvil-parser/commit/e4a460a97229c1833c36a38b180cb0b80e2b26b8
I have not tested this code, I have not updated the tests. I have not updated raw_section.py. Updating those would require some conceptual changes. I am just providing the code in case it helps.
